### PR TITLE
Feat post types

### PR DESCRIPTION
**Pull request by mixcas**
add post types:
- property
- quote (press_quote)

each post type comes with custom metaboxes

### CODE REVIEW

**Review by varffs — CHANGES_REQUESTED** [review]
Quotes need nice url rewrite &/ no permalink at all. Also not sure being clever and removing post_content is sensible. Lots of autogenerated content comes from there like excerpts and social graph stuff. I guess as long as there are no permalinks then that is ok.

**Comment by varffs** [comment]
And while it didn't go straight thru is it worth having the discussion about if we should use posts for properties?

**Comment by mikeyrayvon** [comment]
nice menu icons 👍

**Comment by mikeyrayvon** [comment]
I think its ok to strip the content editor on the Press post type. That doesn't have a single.

**Pull request merged**
