### PR TITLE
Replace swiper

### PR DESCRIPTION
**Pull request by mikeyrayvon**
replace swiper with slick

`bower uninstall swiper --save`
`bower install slick-carousel --save`

### CODE REVIEW

**Comment by varffs** [comment]
I think doing something like swapping a library thing it would be helpful to know why it is happening in the PR

**Comment by varffs** [comment]
This works fine tho. However the filming page is pretty weird on my local:

screen shot 2017-09-05 at 13 19 04

**Comment by varffs** [comment]
Actually I shouldn't have updated this for merge as this doesn't keep the click to progress functionality of the previous gallery and I don't have time to add that rn

**Comment by varffs** [comment]
I'm going to leave it here for the click next functionality to be added as don't want to merge and introduce an issue even if only minor.

**Review by varffs — CHANGES_REQUESTED** [review]
Make gallery progress on click on images/slides

**Comment by mikeyrayvon** [comment]
i'm switching to slick in every open project. i cant achieve the layout I want with swiper. swiper doesn't support variable width slides and i dont want to fight that anymore. it makes for messy layouts and potentially overlapping images

**Pull request merged**
